// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Bibliotech.Api.Models;

public partial class Libro
{
    public int Id { get; set; }

    public string Tittle { get; set; }

    public string PictureLink { get; set; }

    public string Autor { get; set; }

    public string Genero { get; set; }

    public string Isbn { get; set; }

    public DateTime? PublicationDate { get; set; }

    public bool? Disponibilidad { get; set; }

    public DateTime? ExpireDate { get; set; }

    public string Status { get; set; }

    public int? CreationUser { get; set; }

    public DateTime? CreationDate { get; set; }

    public int? ModifyUser { get; set; }

    public DateTime? ModifyDate { get; set; }

    public int? DeleteUser { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool IsDeleted { get; set; }
}