// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bibliotech.Api.Models;

public partial class Notificacion
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Type { get; set; }

    public string Message { get; set; }

    public DateTime FechaEnvio { get; set; }

    public int? CreationUser { get; set; }

    public DateTime? CreationDate { get; set; }

    public int? ModifyUser { get; set; }

    public DateTime? ModifyDate { get; set; }

    public int? DeleteUser { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool IsDeleted { get; set; }
}