// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Bibliotech.Api.Models;

public partial class Reserva
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public int BookId { get; set; }

    public string BookName { get; set; }

    public DateTime? ReservationDate { get; set; }

    public string? Status { get; set; }

    public int? CreationUser { get; set; }

    public DateTime? CreationDate { get; set; }

    public int? ModifyUser { get; set; }

    public DateTime? ModifyDate { get; set; }

    public int? DeleteUser { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool IsDeleted { get; set; }
}