// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>


namespace Bibliotech.Api.Models;

public partial class Role
{
    public int Id { get; set; }

    public string Role1 { get; set; }

    public int? CreationUser { get; set; }

    public DateTime? CreationDate { get; set; }

    public int? ModifyUser { get; set; }

    public DateTime? ModifyDate { get; set; }

    public int? DeleteUser { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool IsDeleted { get; set; }
}