// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bibliotech.Api.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string EMail { get; set; }

    public string Password { get; set; }

    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public int? CreationUser { get; set; }

    public DateTime? CreationDate { get; set; }

    public int? ModifyUser { get; set; }

    public DateTime? ModifyDate { get; set; }

    public int? DeleteUser { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool IsDeleted { get; set; }
}